ft: Add mobile menu
descholar-ceo/mobile-menu pull request #1
Opened 2021-05-21 21:13 UTC by descholar-ceo

## What does this PR do?
It adds a full screen mobile menu

## Tasks to be completed on this PR
- [ ] Setup linters
- [ ] Create and style the fullscreen menu
- [ ] Add js file which will contains js codes to enable toggling fullscreen menu bar
- [ ] Develop logic of hidding and unhiddding full screen menu bar

2021-05-21 22:43 UTC, Dipeshtwis requested changes
Hi @descholar-ceo, 

Good job so far!

Here're the major highlights of this PR:
- Your PR title and description are really descriptive.
- The mobile menu is working as it has to be.

But there are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [x] The menu items color is different on mobile view. "You must stick to the design as much as possible" is one of the project requirements. This involves colors, margins, etc. I suggest you to check the [project design ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A424) and make it like a similar one.
- [x] Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template)  but remember to customize it to your project.

### _Also Check the comments under the review._

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-05-21 22:43 UTC, Dipeshtwis commented on index.html
> +      <p><i id="close-fullscreen-menu-btn" class="fa fa-times" aria-hidden="true"></i></p>
[required]

- [ ] I would suggest you make this a `button`, and not a `p` tag. This is important for accessibility purposes.

2021-05-21 22:43 UTC, Dipeshtwis commented on menu.js
> +    });
[Required]

- [ ] It is important to always keep your code DRY. Here I can see you are repeating the code. I would suggest you make a function and call it whenever you need to implement those functionality. It will make your code cleaner.

2021-05-22 21:44 UTC, descholar-ceo commented on index.html
> +      <p><i id="close-fullscreen-menu-btn" class="fa fa-times" aria-hidden="true"></i></p>
Fixed :heavy_check_mark:

2021-05-22 22:01 UTC, descholar-ceo commented on menu.js
> +    });
Fixed :heavy_check_mark:

2021-05-22 22:54 UTC, arikarim approved these changes
Hello to one of the best Code Reviewers[ Emmanuel ](https://github.com/descholar-ceo) :hand: :smile:  , 

## Status: Approved :rocket: :100: 

Excellent work implementing all the changes required by the previous Code Reviewer'
Your project is complete!, looks and works just fine :smiley: , Your mobile nav looks  nice.  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :rocket:  :smile_cat: 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
or for any questions feel free to contact me on:
Slack`@arikarim`.
Linkedin: [Here](https://www.linkedin.com/in/ari-karim/)

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-05-23 16:14 UTC, descholar-ceo commented
> Hello to one of the best Code Reviewers[ Emmanuel ](https://github.com/descholar-ceo)   ,
> 
> ## Status: Approved  
> Excellent work implementing all the changes required by the previous Code Reviewer'
> Your project is complete!, looks and works just fine  , Your mobile nav looks nice. There is nothing else to say other than... it's time to merge it :shipit:
> Congratulations!   
> 
> Cheers and Happy coding!
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> or for any questions feel free to contact me on:
> Slack`@arikarim`.
> Linkedin: [Here](https://www.linkedin.com/in/ari-karim/)
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you so much @arikarim

2021-05-23 16:14 UTC, merged